//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.CodeCoordinationService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CodeCoordinationService.ICoordination")]
    public interface ICoordination {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/execute", ReplyAction="http://tempuri.org/ICoordination/executeResponse")]
        void execute();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/execute", ReplyAction="http://tempuri.org/ICoordination/executeResponse")]
        System.Threading.Tasks.Task executeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/gentestcase", ReplyAction="http://tempuri.org/ICoordination/gentestcaseResponse")]
        void gentestcase();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/gentestcase", ReplyAction="http://tempuri.org/ICoordination/gentestcaseResponse")]
        System.Threading.Tasks.Task gentestcaseAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/runp", ReplyAction="http://tempuri.org/ICoordination/runpResponse")]
        void runp();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/runp", ReplyAction="http://tempuri.org/ICoordination/runpResponse")]
        System.Threading.Tasks.Task runpAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/runs", ReplyAction="http://tempuri.org/ICoordination/runsResponse")]
        void runs();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/runs", ReplyAction="http://tempuri.org/ICoordination/runsResponse")]
        System.Threading.Tasks.Task runsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/settest", ReplyAction="http://tempuri.org/ICoordination/settestResponse")]
        void settest(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/settest", ReplyAction="http://tempuri.org/ICoordination/settestResponse")]
        System.Threading.Tasks.Task settestAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setcasegen", ReplyAction="http://tempuri.org/ICoordination/setcasegenResponse")]
        void setcasegen(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setcasegen", ReplyAction="http://tempuri.org/ICoordination/setcasegenResponse")]
        System.Threading.Tasks.Task setcasegenAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setcodep", ReplyAction="http://tempuri.org/ICoordination/setcodepResponse")]
        void setcodep(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setcodep", ReplyAction="http://tempuri.org/ICoordination/setcodepResponse")]
        System.Threading.Tasks.Task setcodepAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setcodes", ReplyAction="http://tempuri.org/ICoordination/setcodesResponse")]
        void setcodes(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setcodes", ReplyAction="http://tempuri.org/ICoordination/setcodesResponse")]
        System.Threading.Tasks.Task setcodesAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setopp", ReplyAction="http://tempuri.org/ICoordination/setoppResponse")]
        void setopp(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setopp", ReplyAction="http://tempuri.org/ICoordination/setoppResponse")]
        System.Threading.Tasks.Task setoppAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setops", ReplyAction="http://tempuri.org/ICoordination/setopsResponse")]
        void setops(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setops", ReplyAction="http://tempuri.org/ICoordination/setopsResponse")]
        System.Threading.Tasks.Task setopsAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/settestl", ReplyAction="http://tempuri.org/ICoordination/settestlResponse")]
        void settestl(SupportedLanguage.language lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/settestl", ReplyAction="http://tempuri.org/ICoordination/settestlResponse")]
        System.Threading.Tasks.Task settestlAsync(SupportedLanguage.language lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setcodepl", ReplyAction="http://tempuri.org/ICoordination/setcodeplResponse")]
        void setcodepl(SupportedLanguage.language lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setcodepl", ReplyAction="http://tempuri.org/ICoordination/setcodeplResponse")]
        System.Threading.Tasks.Task setcodeplAsync(SupportedLanguage.language lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setcodesl", ReplyAction="http://tempuri.org/ICoordination/setcodeslResponse")]
        void setcodesl(SupportedLanguage.language lang);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICoordination/setcodesl", ReplyAction="http://tempuri.org/ICoordination/setcodeslResponse")]
        System.Threading.Tasks.Task setcodeslAsync(SupportedLanguage.language lang);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICoordinationChannel : Client.CodeCoordinationService.ICoordination, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CoordinationClient : System.ServiceModel.ClientBase<Client.CodeCoordinationService.ICoordination>, Client.CodeCoordinationService.ICoordination {
        
        public CoordinationClient() {
        }
        
        public CoordinationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CoordinationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoordinationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CoordinationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void execute() {
            base.Channel.execute();
        }
        
        public System.Threading.Tasks.Task executeAsync() {
            return base.Channel.executeAsync();
        }
        
        public void gentestcase() {
            base.Channel.gentestcase();
        }
        
        public System.Threading.Tasks.Task gentestcaseAsync() {
            return base.Channel.gentestcaseAsync();
        }
        
        public void runp() {
            base.Channel.runp();
        }
        
        public System.Threading.Tasks.Task runpAsync() {
            return base.Channel.runpAsync();
        }
        
        public void runs() {
            base.Channel.runs();
        }
        
        public System.Threading.Tasks.Task runsAsync() {
            return base.Channel.runsAsync();
        }
        
        public void settest(string name) {
            base.Channel.settest(name);
        }
        
        public System.Threading.Tasks.Task settestAsync(string name) {
            return base.Channel.settestAsync(name);
        }
        
        public void setcasegen(string name) {
            base.Channel.setcasegen(name);
        }
        
        public System.Threading.Tasks.Task setcasegenAsync(string name) {
            return base.Channel.setcasegenAsync(name);
        }
        
        public void setcodep(string name) {
            base.Channel.setcodep(name);
        }
        
        public System.Threading.Tasks.Task setcodepAsync(string name) {
            return base.Channel.setcodepAsync(name);
        }
        
        public void setcodes(string name) {
            base.Channel.setcodes(name);
        }
        
        public System.Threading.Tasks.Task setcodesAsync(string name) {
            return base.Channel.setcodesAsync(name);
        }
        
        public void setopp(string name) {
            base.Channel.setopp(name);
        }
        
        public System.Threading.Tasks.Task setoppAsync(string name) {
            return base.Channel.setoppAsync(name);
        }
        
        public void setops(string name) {
            base.Channel.setops(name);
        }
        
        public System.Threading.Tasks.Task setopsAsync(string name) {
            return base.Channel.setopsAsync(name);
        }
        
        public void settestl(SupportedLanguage.language lang) {
            base.Channel.settestl(lang);
        }
        
        public System.Threading.Tasks.Task settestlAsync(SupportedLanguage.language lang) {
            return base.Channel.settestlAsync(lang);
        }
        
        public void setcodepl(SupportedLanguage.language lang) {
            base.Channel.setcodepl(lang);
        }
        
        public System.Threading.Tasks.Task setcodeplAsync(SupportedLanguage.language lang) {
            return base.Channel.setcodeplAsync(lang);
        }
        
        public void setcodesl(SupportedLanguage.language lang) {
            base.Channel.setcodesl(lang);
        }
        
        public System.Threading.Tasks.Task setcodeslAsync(SupportedLanguage.language lang) {
            return base.Channel.setcodeslAsync(lang);
        }
    }
}
